services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:6       # ✅ Correct Mongo image
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node API service
  api:
    build: .             # ✅ Build the image from your Dockerfile
    container_name: nodeapp
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db

volumes:
  mongo_data:
