"""
Django settings for djangoproj project.
Generated by 'django-admin startproject' using Django 3.2.5.
"""

import os
from pathlib import Path

# -------------------------------------------------------------
# Base Directory
# -------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------
# Security
# -------------------------------------------------------------
SECRET_KEY = "django-insecure-ccow$tz_=9%dxu4(0%^(z%nx32#s@(zt9$ih@)5l54yny)wm-0"
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    (
        "u31241596-8000.theiadockernext-0-labs-prod-"
        "theiak8s-4-tor01.proxy.cognitiveclass.ai"
    ),
    (
        "u31241596-8000.theianext-0-labs-prod-misc-tools-"
        "us-east-0.proxy.cognitiveclass.ai"
    ),
]

CSRF_TRUSTED_ORIGINS = [
    (
        "https://u31241596-8000.theiadockernext-0-labs-prod-"
        "theiak8s-4-tor01.proxy.cognitiveclass.ai"
    ),
    (
        "https://u31241596-8000.theianext-0-labs-prod-misc-tools-"
        "us-east-0.proxy.cognitiveclass.ai"
    ),
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
}

# -------------------------------------------------------------
# Applications
# -------------------------------------------------------------
INSTALLED_APPS = [
    "djangoapp.apps.DjangoappConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# -------------------------------------------------------------
# Middleware
# -------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djangoproj.urls"

# -------------------------------------------------------------
# Templates
# -------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            # React build output directory
            os.path.join(BASE_DIR, "frontend/build"),
            # Optional: templates inside static folder (e.g., Home.html)
            os.path.join(BASE_DIR, "frontend/static"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoproj.wsgi.application"

# -------------------------------------------------------------
# Database
# -------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -------------------------------------------------------------
# Password Validation
# -------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        )
    },
    {"NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator")},
    {"NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator")},
    {"NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator")},
]

# -------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# -------------------------------------------------------------
# Static & Media Files
# -------------------------------------------------------------
STATIC_URL = "/static/"

# Location where collectstatic will copy files
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Additional directories Django will look for static files
STATICFILES_DIRS = [
    # React build root
    os.path.join(BASE_DIR, "frontend/build"),
    # JS/CSS assets
    os.path.join(BASE_DIR, "frontend/build/static"),
    # Extra static files
    os.path.join(BASE_DIR, "frontend/static"),
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# -------------------------------------------------------------
# Default Primary Key
# -------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
